export const VALIDAR_FORMULARIO = 'VALIDAR_FORMULARIO';
export const VALIDAR_FORMULARIO_EXITO = 'VALIDAR_FORMULARIO_EXITO';
export const VALIDAR_FORMULARIO_ERROR = 'VALIDAR_FORMULARIO_ERROR';

export const AGREGAR_LIBRO = 'AGREGAR_LIBRO';
export const AGREGAR_LIBRO_EXITO = 'AGREGAR_LIBRO_EXITO';
export const AGREGAR_LIBRO_ERROR = 'AGREGAR_LIBRO_ERROR';

export const COMENZAR_DESCARGA_LIBROS = 'COMENZAR_DESCARGA_LIBROS';
export const COMENZAR_DESCARGA_EXITOSA = 'COMENZAR_DESCARGA_EXITOSA';
export const COMENZAR_DESCARGA_ERROR = 'COMENZAR_DESCARGA_ERROR';

export const OBTENER_LIBRO_ELIMINAR = 'OBTENER_LIBRO_ELIMINAR';
export const LIBRO_ELIMINADO_EXITO = 'LIBRO_ELIMINADO_EXITO';
export const LIBRO_ELIMINADO_ERROR = 'LIBRO_ELIMINADO_ERROR';

export const OBTENER_LIBRO_EDITAR = 'OBTENER_LIBRO_EDITAR';
export const LIBRO_EDTIAR_EXITO = 'LIBRO_EDTIAR_EXITO';
export const LIBRO_EDTIAR_ERROR = 'LIBRO_EDTIAR_ERROR';

export const COMENZAR_EDICION_LIBRO = 'COMENZAR_EDICION_LIBRO';
export const LIBRO_EDICION_EXITO = 'LIBRO_EDICION_EXITO';
export const LIBRO_EDICION_ERROR = 'LIBRO_EDICION_ERROR';